export const initialState = {
    genres: [
        'essay',
        'article',
        'blog',
        'book',
        'letter',
        'story',
        'poem',
        'script',
        'speech',
        'other',
    ],
    themes: [
        'AI',
        'space',
        'time',
        'love',
        'life',
        'death',
        'nature',
        'war',
        'peace',
        'other',
    ],
    styles: [
        'MLA',
        'APA',
        'Chicago',
        'Harvard',
        'Turabian',
        'IEEE',
        'other',
    ],
    text: '',
    completions: [],
    enableAI: false,
    selectedLanguage: 'en',
    selectedWordCount: '500',
    selectedGenre: 'essay',
    selectedTheme: 'AI',
    selectedStyle: 'MLA',
    selectedPrompt: 'Write an essay about the future of AI.',
};
