import { editorDefaults } from "../constants/editorDefaults";

export const initialState = {
    genres: [
        'essay',
        'article',
        'blog',
        'book',
        'letter',
        'story',
        'poem',
        'script',
        'speech',
        'other',
    ],
    themes: [
        'space',
        'time',
        'love',
        'life',
        'happiness',
        'success',
        'communication',
        'learning',
        'knowledge',
        'wisdom',
        'intelligence',
        'consciousness',
        'mindfulness',
        'meditation',
        'spirituality',
        'emotions',
        'dreams',
        'imagination',
        'creativity',
        'freedom',
        'justice',
        'equality',
        'mind',
        'body',
        'death',
        'nature',
        'animals',
        'family',
        'friendship',
        'travel',
        'food',
        'music',
        'movies',
        'sports',
        'health',
        'fitness',
        'beauty',
        'technology',
        'politics',
        'religion',
        'history',
        'science',
        'art',
        'work',
        'war',
        'peace',
        'other',
    ],
    styles: [
        'MLA',
        'APA',
        'Chicago',
        'Harvard',
        'Turabian',
        'IEEE',
        'Vancouver',
        'Magical Realism',
        'Gothic',
        'Romantic',
        'Victorian',
        'Modernist',
        'Postmodernist',
        'Minimalist',
        'Surrealist',
        'Realist',
        'Naturalist',
        'Absurdist',
        'other',
    ],
    content: editorDefaults.defaultContent,
    completions: [],
    completionsHistory: [],
    currentFile: editorDefaults.currentFile,
    files: editorDefaults.files,
    enableAI: editorDefaults.enableAI,
    selectedGenre: editorDefaults.selectedGenre,
    selectedTheme: editorDefaults.selectedTheme,
    selectedStyle: editorDefaults.selectedStyle,
    selectedTab: editorDefaults.selectedTab,
    selectedLanguage: editorDefaults.selectedLanguage,
    selectedWordCount: editorDefaults.selectedWordCount,
 };
