import { editorDefaults } from "../constants/editorDefaults";

export const initialState = {
    genres: [
        'blog',
        'tweet',
        'essay',
        'article',
        'commentary',
        'journal',
        'diary',
        'note',
        'email',
        'message',
        'letter',
        'book',
        'story',
        'poem',
        'script',
        'speech',
        'report',
        'proposal',
        'manual',
        'guide',
        'tutorial',
        'review',
        'summary',
        'abstract',
        'synopsis',
        'analysis',
        'critique',
        'document',       
        'text',
        'other',
    ],
    themes: [
        'space',
        'time',
        'love',
        'life',
        'happiness',
        'success',
        'communication',
        'learning',
        'knowledge',
        'wisdom',
        'intelligence',
        'consciousness',
        'mindfulness',
        'meditation',
        'spirituality',
        'emotions',
        'dreams',
        'imagination',
        'creativity',
        'freedom',
        'justice',
        'equality',
        'mind',
        'body',
        'death',
        'nature',
        'animals',
        'family',
        'friendship',
        'travel',
        'food',
        'music',
        'movies',
        'sports',
        'health',
        'fitness',
        'beauty',
        'technology',
        'politics',
        'religion',
        'history',
        'science',
        'art',
        'work',
        'war',
        'peace',
        'other',
    ],
    styles: [
        'MLA',
        'APA',
        'Chicago',
        'Harvard',
        'Turabian',
        'IEEE',
        'Vancouver',
        'Magical Realism',
        'Gothic',
        'Romantic',
        'Victorian',
        'Modernist',
        'Postmodernist',
        'Minimalist',
        'Surrealist',
        'Realist',
        'Naturalist',
        'Absurdist',
        'Existentialist',
        'Satirical',
        'Parodic',
        'Metafictional',
        'Historical',
        'Biographical',
        'Autobiographical',
        'Journalistic',
        'Documentary',
        'Scientific',
        'Technical',
        'Legal',
        'Medical',
        'Business',
        'Sarcastic',
        'Irony', 
        'other',
    ],
    firstEditorUpdate: true,
    content: editorDefaults.defaultContent,
    currentFile: editorDefaults.currentFile,
    files: editorDefaults.files,
    enableAI: editorDefaults.enableAI,
    selectedGenre: editorDefaults.selectedGenre,
    selectedTheme: editorDefaults.selectedTheme,
    selectedStyle: editorDefaults.selectedStyle,
    selectedTab: editorDefaults.selectedTab,
    selectedLanguage: editorDefaults.selectedLanguage,
    selectedWordCount: editorDefaults.selectedWordCount,
 };
